import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Nuno",
      email: "nuno_fernandes18@hotmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jebo",
      email: "jebo@hotmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: "Vinylmatt",
      slug: "cin.vinylmatt",
      category: "Tinta",
      image: "images/sd.webp", //dimensions 679 x 829
      price: 80,
      countInStock: 10,
      brand: "CIN",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      // _id: '2',
      name: "Vinyclean",
      slug: "cin.vinyclean",
      category: "Tinta",
      image: "images/sd.webp",
      price: 80,
      countInStock: 4,
      brand: "CIN",
      rating: 3.0,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      //_id: '3',
      name: "Nike Pants",
      slug: "nike.slim.pants",
      category: "Pants",
      image: "images/sd.webp",
      price: 25,
      countInStock: 15,
      brand: "CIN",
      rating: 4.5,
      numReviews: 14,
      description: "hight quality pants",
    },
    {
      //_id: '4',
      name: "s ss",
      slug: "puma.fit.pants",
      category: "Pants",
      image: "images/sd.webp",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality pants",
    },
    {
      //_id: '4',
      name: "s asasss",
      slug: "puma.fit.pantsh",
      category: "Pants",
      image: "images/sd.webp",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality pants",
    },
    {
      //_id: '4',
      name: "s asasasasss",
      slug: "puma.fit.paassantsh",
      category: "Pants",
      image: "images/sd.webp",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality pants",
    },
    {
      //_id: '4',
      name: "s asdfgsasss",
      slug: "puma.fit.panthhsh",
      category: "Pants",
      image: "images/sd.webp",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality pants",
    },
    {
      //_id: '4',
      name: "s aaaasfsasss",
      slug: "puma.fit.paggntsh",
      category: "Pants",
      image: "images/sd.webp",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality pants",
    },
    {
      //_id: '4',
      name: "ssdfggggsas",
      slug: "puma.fit.panthhhjhsh",
      category: "Pants",
      image: "images/sd.webp",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality pants",
    },
    {
      //_id: '4',
      name: "ssdfgsaiss",
      slug: "puma.fit.pantdfghhsh",
      category: "Pants",
      image: "images/sd.webp",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality pants",
    },
  ],
};
export default data;
